### ISSUE TITLE
a thorough guide would be helpful

### ISSUE THREAD

**Issue by italianjesus** [patxijuaristi/website_email_scraper#1]
I want to use it but I can’t seem to get it working.

![Screenshot_1](https://user-images.githubusercontent.com/54536994/158404645-297fe63f-17ac-49bf-a435-23bcabe20e97.png)

**Comment by patxijuaristi** [comment]
Hi!!

First of all you need to install the requirements.

`pip install -r requirements.txt`

Then in the same directory of the _email_scraper.py_ you need to have the _webpages.txt_ file with all the urls you want to scrape.

Then just execute the script. If you have python added in the machine path you just need to type:

**`email_scraper.py EN`**

Maybe the problem is because you are typing the "EN" in lowercase. Write the **EN** in capital letters. Anyway I will do a commit now to work with lowercase.

Best regards!

**Comment by italianjesus** [comment]
That fixes the problem! Thank you!
