### ISSUE TITLE
more attributes?

### ISSUE THREAD

**Issue by italianjesus** [patxijuaristi/website_email_scraper#2]
I don’t know how to phrase it correctly but, the script seems to only check 3 possible link combinations. Adding more endings like “support” or “contactus” will make the script probably more effective. 

And giving every ending also an “.html” ending will be good too. Like: 
“www.example.com/contact” 
“www.example.com/contact.html”

![image](https://user-images.githubusercontent.com/54536994/158436812-c6f6daf6-a8e5-4d63-980c-b9410441c8bc.png)

**Comment by patxijuaristi** [comment]
Yeah, you are right. However, I have added only those url endings to make the scraping process faster when you want to scrape large amount of urls. Because if you add more options, needs to do more checking for each url.

If you want to add your custom url endings you can do it **simply chaning the 66th line of email_scraper.py**.

`listaPaginas=['contact','contact-us','contact-us.html','your_custom_ending1', 'your_custom_ending2', 'your_custom_ending3']`
